Added music links to Tidal
ericlewis/Ai-Pin pull request #22
Opened 2024-04-30 17:37 UTC by Diegogtz03

- Modified music event model to receive optional trackID
- Added links to songs that redirect to Tidal

2024-04-30 18:37 UTC, ericlewis commented on PinKit/Sources/PinKit/My Data/Cells/MusicCellView.swift
> +                        openURL(trackUrl)
right above this (line 38) you should do: `else if let trackId = event.trackID`, otherwise we have a button that doesn't do anything.

2024-04-30 18:38 UTC, ericlewis requested changes
correctly unwrap trackId

2024-04-30 18:48 UTC, Diegogtz03 commented
Added this second case to add a button, and added the default case to just render the Labeled Content. Lmk if this looks good!

2024-04-30 18:54 UTC, Diegogtz03 commented
Actually... I guess if it's not a playlist it should always have a trackid right? So we should just be good with those 2 cases then... what do you think? Just leave the playlist and else or keep that third one just in case?

2024-04-30 19:08 UTC, Diegogtz03 commented
In case we want to keep the 3 cases, I could make a View for the shared label and just call a button with that label on the case where a trackId exists.

2024-04-30 20:16 UTC, ericlewis commented
> In case we want to keep the 3 cases, I could make a View for the shared label and just call a button with that label on the case where a trackId exists.

we do want the 3 cases. so yeah, making a view to share with the last 2 cases it fine.

2024-04-30 22:05 UTC, Diegogtz03 commented
There we go!

2024-04-30 22:42 UTC, Diegogtz03 commented
Trying to fix Smart Playlist parsing... looks like adding the TrackId breaks the playlists, but I think I found why. Fixing now.

2024-04-30 23:17 UTC, Diegogtz03 commented
So it's now fixed, but it's having trouble managing both a button and a NavigationLink on the same list

2024-05-01 04:02 UTC, ericlewis approved these changes

2024-05-01 04:02 UTC, merged